<?php
/**
 * Ad list page
 * @author oneTarek
 * @since 2.0.0
 */

// Don't allow direct access
if ( ! defined( 'ABSPATH' ) ) exit;

if( wp_get_referer() && isset( $_GET['msg'] ) && $_GET['msg'] != "" )
{
	if( $_GET['msg'] == "deleted")
	{
		adguru()->admin_notice->render( "Ad has been deleted successfully", array( "type"=>"success", "dismissible"=>true ) );
	}
}

require_once ADGURU_PLUGIN_DIR . 'includes/admin/class-adguru-ad-list-table.php';
$args = array(
	'singular' 	=> $current_ad_type_args['name'],
	'plural'   	=> $current_ad_type_args['plural_name'],
	'ad_type'	=> $current_ad_type,
	'base_url' 	=> $base_url
);
$ad_list_table = new ADGURU_Ad_List_Table( $args );
$ad_list_table->prepare_items();

?>		
<form id="adguru-ad-search-form" method="get" action="<?php echo $base_url; ?>" style="margin-top:5px;">
	<?php $ad_list_table->search_box( __( 'Search', 'adguru' ), 'adguru_ad_search_input' ); ?>

	<input type="hidden" name="manager_tab" value="<?php echo $current_manager_tab ?>" />
	<input type="hidden" name="page" value="<?php echo $page ?>" />
	

	<?php $ad_list_table->views() ?>
	<?php $ad_list_table->display() ?>
	
</form>
<style type="text/css">
	.wp-list-table .column-ID{ width:5%; }
</style>

<!-- Start Get Code Modal -->
<div id="ad_code_modal" title="Get Code">
	<div id="ad_code_content">
			<strong><?php _e( 'PHP CODE', 'adguru' ) ?></strong><BR />
			<code id="ad_code_php"></code><BR /><BR />
			<strong><?php _e( 'SHORTCODE', 'adguru' ) ?></strong><BR />
			<code id="ad_code_shortcode"></code>
		<!--content will be generated by javascript-->
	</div>			
</div>
<script type="text/javascript">
	jQuery(document).ready(function($){
		
		$( "#ad_code_modal" ).dialog({
			height: 230,
			width: 600,
			modal: true,
			autoOpen: false,
			buttons: {
				Cancel: function() {$( this ).dialog( "close" );}
				}		
		});//END DIALOG
				
	}); //end document ready
		
	function show_ad_code_modal(adid , name)
	{
		var php_code="&lt;?php if(function_exists('adguru_ad')){adguru_ad("+adid+");} ?&gt;";
		var shortcode='[adguru adid="'+adid+'"]';
		jQuery("#ad_code_php").html(php_code);
		jQuery("#ad_code_shortcode").html(shortcode);
		jQuery( "#ad_code_modal" ).dialog( { title: "Get Code for : "+name });
		jQuery( "#ad_code_modal" ).dialog( "open" );
		return false;
	}			
</script>
<!-- End Get Code Modal -->


